# Generated by Django 5.2.12 on 2026-03-13 08:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0001_initial"),
        ("multitenant", "0003_branding"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="forum",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="forum",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="forum",
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-is_answer", "created_at"]},
        ),
        migrations.AlterModelOptions(
            name="topic",
            options={"ordering": ["-is_pinned", "-last_activity_at"]},
        ),
        migrations.AddField(
            model_name="post",
            name="is_answer",
            field=models.BooleanField(
                default=False, help_text="Accepted answer for Q topics"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="like_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="post",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="community.post",
            ),
        ),
        migrations.AddField(
            model_name="topic",
            name="content_mdx",
            field=models.TextField(blank=True, default="", help_text="MDX content"),
        ),
        migrations.AddField(
            model_name="topic",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="topic",
            name="is_answered",
            field=models.BooleanField(default=False, help_text="For question topics"),
        ),
        migrations.AddField(
            model_name="topic",
            name="last_activity_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="topic",
            name="like_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="topic",
            name="reply_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="topic",
            name="slug",
            field=models.SlugField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="topic",
            name="topic_type",
            field=models.CharField(
                choices=[
                    ("discussion", "Discussion"),
                    ("question", "Question"),
                    ("poll", "Poll"),
                    ("announcement", "Announcement"),
                ],
                default="discussion",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="topic",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="topic",
            name="view_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(help_text="MDX content"),
        ),
        migrations.AlterField(
            model_name="post",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="community_posts",
                to="multitenant.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="topic",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="community_topics",
                to="multitenant.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="topic",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name="MemberProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.TextField(blank=True, default="", max_length=500)),
                ("avatar_url", models.URLField(blank=True, default="")),
                ("points", models.PositiveIntegerField(default=0)),
                ("level", models.PositiveSmallIntegerField(default=1)),
                ("topics_created", models.PositiveIntegerField(default=0)),
                ("posts_created", models.PositiveIntegerField(default=0)),
                ("likes_received", models.PositiveIntegerField(default=0)),
                ("likes_given", models.PositiveIntegerField(default=0)),
                ("joined_community_at", models.DateTimeField(auto_now_add=True)),
                ("last_active_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="community_profiles",
                        to="multitenant.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="community_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-points"],
            },
        ),
        migrations.CreateModel(
            name="Reaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reaction_type",
                    models.CharField(
                        choices=[
                            ("like", "👍"),
                            ("love", "❤️"),
                            ("insightful", "💡"),
                            ("celebrate", "🎉"),
                        ],
                        default="like",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="community_reactions",
                        to="multitenant.tenant",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="community.post",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="community.topic",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="community_reactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Space",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("name_en", models.CharField(max_length=200, null=True)),
                ("name_es", models.CharField(max_length=200, null=True)),
                ("name_pt", models.CharField(max_length=200, null=True)),
                ("slug", models.SlugField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("description_en", models.TextField(blank=True, default="", null=True)),
                ("description_es", models.TextField(blank=True, default="", null=True)),
                ("description_pt", models.TextField(blank=True, default="", null=True)),
                (
                    "icon_emoji",
                    models.CharField(blank=True, default="💬", max_length=10),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, help_text="Default space for new members"
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                ("is_public", models.BooleanField(default=True)),
                (
                    "requires_level",
                    models.PositiveIntegerField(
                        default=0, help_text="Minimum member level to access"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="community_spaces",
                        to="multitenant.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "name"],
            },
        ),
        migrations.AddField(
            model_name="topic",
            name="space",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="topics",
                to="community.space",
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="topic",
            index=models.Index(
                fields=["organization", "space", "-last_activity_at"],
                name="community_t_organiz_57af02_idx",
            ),
        ),
        migrations.DeleteModel(
            name="Forum",
        ),
        migrations.AlterUniqueTogether(
            name="memberprofile",
            unique_together={("organization", "user")},
        ),
        migrations.AddConstraint(
            model_name="reaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("topic__isnull", False)),
                fields=("user", "topic", "reaction_type"),
                name="unique_topic_reaction",
            ),
        ),
        migrations.AddConstraint(
            model_name="reaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("post__isnull", False)),
                fields=("user", "post", "reaction_type"),
                name="unique_post_reaction",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="space",
            unique_together={("organization", "slug")},
        ),
    ]
