name: 🐛 Bug Report / Reporte de Bug
description: Reporta un error o comportamiento inesperado / Report an error or unexpected behavior
title: "[BUG] "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🇪🇸 Español / 🇺🇸 English
        
        Puedes escribir en español o inglés. / You can write in Spanish or English.
        
        Gracias por reportar este bug. Por favor completa toda la información posible para ayudarnos a reproducir y solucionar el problema.
        
        Thank you for reporting this bug. Please complete as much information as possible to help us reproduce and fix the issue.

  - type: checkboxes
    id: preliminary-checks
    attributes:
      label: ✅ Verificaciones Preliminares / Preliminary Checks
      description: Por favor confirma que has realizado estas verificaciones / Please confirm you have done these checks
      options:
        - label: He buscado en los issues existentes y no encontré uno similar / I searched existing issues and didn't find a similar one
          required: true
        - label: Este bug es reproducible / This bug is reproducible
          required: true
        - label: He leído la documentación / I have read the documentation
          required: true

  - type: textarea
    id: bug-description
    attributes:
      label: 🐛 Descripción del Bug / Bug Description
      description: Describe claramente qué está pasando / Clearly describe what's happening
      placeholder: |
        Ejemplo / Example:
        Cuando intento crear un nuevo usuario, la API devuelve un error 500 en lugar de crear el usuario.
        
        When I try to create a new user, the API returns a 500 error instead of creating the user.
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: ✅ Comportamiento Esperado / Expected Behavior
      description: Qué esperabas que pasara? / What did you expect to happen?
      placeholder: |
        Ejemplo / Example:
        El usuario debería crearse exitosamente y devolver un status 201 con los datos del usuario.
        
        The user should be created successfully and return a 201 status with user data.
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: 🔄 Pasos para Reproducir / Steps to Reproduce
      description: Pasos detallados para reproducir el problema / Detailed steps to reproduce the issue
      placeholder: |
        1. Ir a la página de registro / Go to registration page
        2. Llenar el formulario con datos válidos / Fill form with valid data  
        3. Hacer click en "Crear Usuario" / Click "Create User"
        4. Ver el error en la consola / See error in console
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: 🧩 Componente Afectado / Affected Component
      description: Qué parte del sistema está afectada? / Which part of the system is affected?
      options:
        - Frontend (Next.js)
        - Backend (FastAPI)
        - Base de Datos / Database (PostgreSQL)
        - Autenticación / Authentication
        - API
        - UI/UX
        - Documentación / Documentation
        - Docker/DevOps
        - Otro / Other
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: 🚨 Severidad / Severity
      description: Qué tan crítico es este bug? / How critical is this bug?
      options:
        - 🔴 Crítico - Sistema no funciona / Critical - System doesn't work
        - 🟠 Alto - Funcionalidad importante rota / High - Important functionality broken
        - 🟡 Medio - Problema menor pero notable / Medium - Minor but noticeable issue
        - 🟢 Bajo - Cosmético o edge case / Low - Cosmetic or edge case
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: 🖥️ Información del Sistema / System Information
      description: Información sobre tu entorno / Information about your environment
      value: |
        **Proyecto Semilla Version / Version**: 
        **OS**: 
        **Browser / Navegador**: 
        **Docker Version**: 
        **PostgreSQL Version**: 
        **Python Version**: 
        **Node.js Version**: 
      render: markdown
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: 📋 Logs y Errores / Logs and Errors
      description: Incluye logs relevantes, stack traces, o mensajes de error / Include relevant logs, stack traces, or error messages
      render: shell

  - type: textarea
    id: screenshots
    attributes:
      label: 📸 Screenshots/Videos
      description: Si aplica, adjunta screenshots o videos / If applicable, attach screenshots or videos

  - type: textarea
    id: additional-context
    attributes:
      label: 📝 Contexto Adicional / Additional Context
      description: Cualquier información adicional que pueda ser útil / Any additional information that might be helpful

  - type: checkboxes
    id: contribution
    attributes:
      label: 🤝 Contribución / Contribution
      description: ¿Estarías interesado en ayudar a solucionarlo? / Would you be interested in helping fix this?
      options:
        - label: Me gustaría trabajar en una solución para este problema / I would like to work on a solution for this issue
        - label: Puedo proporcionar más información si es necesaria / I can provide more information if needed