name: ✨ Feature Request / Solicitud de Característica
description: Sugiere una nueva característica o mejora / Suggest a new feature or enhancement
title: "[FEATURE] "
labels: ["enhancement", "needs-discussion"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🇪🇸 Español / 🇺🇸 English
        
        Puedes escribir en español o inglés. / You can write in Spanish or English.
        
        Gracias por sugerir una nueva característica. Esto nos ayuda a hacer que Proyecto Semilla sea mejor para todos.
        
        Thank you for suggesting a new feature. This helps us make Proyecto Semilla better for everyone.

  - type: checkboxes
    id: preliminary-checks
    attributes:
      label: ✅ Verificaciones Preliminares / Preliminary Checks
      description: Por favor confirma que has realizado estas verificaciones / Please confirm you have done these checks
      options:
        - label: He buscado en los issues existentes y discussions / I searched existing issues and discussions
          required: true
        - label: He revisado el roadmap del proyecto / I have reviewed the project roadmap
          required: true
        - label: Esta característica está alineada con la filosofía del proyecto / This feature aligns with the project philosophy
          required: true

  - type: textarea
    id: feature-summary
    attributes:
      label: 💡 Resumen de la Característica / Feature Summary
      description: Describe brevemente la característica que propones / Briefly describe the feature you're proposing
      placeholder: |
        Ejemplo / Example:
        Agregar soporte para autenticación con redes sociales (Google, GitHub, etc.)
        
        Add support for social media authentication (Google, GitHub, etc.)
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: 🎯 Problema o Necesidad / Problem or Need
      description: ¿Qué problema resuelve esta característica? / What problem does this feature solve?
      placeholder: |
        Ejemplo / Example:
        Los usuarios actuales tienen que recordar otra contraseña, lo cual es inconveniente y reduce la adopción.
        
        Current users have to remember another password, which is inconvenient and reduces adoption.
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: 💻 Solución Propuesta / Proposed Solution
      description: Describe detalladamente cómo funcionaría esta característica / Describe in detail how this feature would work
      placeholder: |
        Ejemplo / Example:
        - Agregar botones "Continuar con Google/GitHub" en la página de login
        - Implementar OAuth 2.0 flow en el backend
        - Vincular cuentas sociales con usuarios existentes
        - Configurar providers en variables de entorno
        
        - Add "Continue with Google/GitHub" buttons on login page
        - Implement OAuth 2.0 flow in backend
        - Link social accounts with existing users
        - Configure providers in environment variables
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: 🧩 Componente Afectado / Affected Component
      description: Qué parte del sistema necesitaría cambios? / Which part of the system would need changes?
      options:
        - Frontend (Next.js)
        - Backend (FastAPI)
        - Base de Datos / Database (PostgreSQL)
        - Autenticación / Authentication
        - API
        - UI/UX
        - Documentación / Documentation
        - Docker/DevOps
        - Múltiples componentes / Multiple components
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: 🚨 Prioridad / Priority
      description: Qué prioridad crees que debería tener? / What priority do you think this should have?
      options:
        - 🔴 Alta - Crítico para el éxito del proyecto / High - Critical for project success
        - 🟠 Media-Alta - Muy importante / Medium-High - Very important
        - 🟡 Media - Sería bueno tenerlo / Medium - Would be nice to have
        - 🟢 Baja - Puede esperar / Low - Can wait
    validations:
      required: true

  - type: dropdown
    id: roadmap-phase
    attributes:
      label: 🗺️ Fase del Roadmap / Roadmap Phase
      description: En qué fase del roadmap crees que encaja? / Which roadmap phase do you think this fits?
      options:
        - "Fase 1 (v0.1.0-v0.3.0): Fundación / Phase 1: Foundation"
        - "Fase 2 (v0.4.0-v0.6.0): Flexibilidad / Phase 2: Flexibility"  
        - "Fase 3 (v0.7.0-v0.9.0): Ecosistema / Phase 3: Ecosystem"
        - "Post v0.9.0: Futuro / Future"
        - "No estoy seguro / Not sure"

  - type: textarea
    id: alternatives
    attributes:
      label: 🔄 Alternativas Consideradas / Alternatives Considered
      description: ¿Hay otras formas de resolver este problema? / Are there other ways to solve this problem?
      placeholder: |
        Ejemplo / Example:
        - Usar un servicio third-party como Auth0
        - Implementar solo Google OAuth inicialmente
        - Crear un plugin/módulo separado
        
        - Use a third-party service like Auth0
        - Implement only Google OAuth initially
        - Create a separate plugin/module

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: ✅ Criterios de Aceptación / Acceptance Criteria
      description: ¿Cómo sabríamos que esta característica está completa? / How would we know this feature is complete?
      placeholder: |
        Ejemplo / Example:
        - [ ] Usuario puede registrarse con Google/GitHub
        - [ ] Cuentas existentes pueden vincular redes sociales
        - [ ] Email de la red social coincide con email existente
        - [ ] Documentación actualizada
        - [ ] Tests implementados
        
        - [ ] User can register with Google/GitHub  
        - [ ] Existing accounts can link social networks
        - [ ] Social media email matches existing email
        - [ ] Documentation updated
        - [ ] Tests implemented

  - type: textarea
    id: mockups
    attributes:
      label: 🎨 Mockups o Ejemplos / Mockups or Examples
      description: Si tienes mockups, wireframes o ejemplos, compártelos / If you have mockups, wireframes or examples, share them

  - type: checkboxes
    id: impact
    attributes:
      label: 📊 Impacto Esperado / Expected Impact
      description: ¿Qué impacto tendría esta característica? / What impact would this feature have?
      options:
        - label: Mejoraría la experiencia del usuario / Would improve user experience
        - label: Aumentaría la adopción del proyecto / Would increase project adoption
        - label: Reduciría la fricción en el onboarding / Would reduce onboarding friction
        - label: Sería diferenciador competitivo / Would be a competitive differentiator
        - label: Simplificaría el desarrollo / Would simplify development
        - label: Mejoraría la seguridad / Would improve security

  - type: checkboxes
    id: contribution
    attributes:
      label: 🤝 Contribución / Contribution
      description: ¿Te gustaría ayudar a implementar esta característica? / Would you like to help implement this feature?
      options:
        - label: Me gustaría implementar esta característica / I would like to implement this feature
        - label: Puedo ayudar con el diseño/planning / I can help with design/planning
        - label: Puedo ayudar con testing / I can help with testing
        - label: Puedo ayudar con documentación / I can help with documentation

  - type: textarea
    id: additional-context
    attributes:
      label: 📝 Contexto Adicional / Additional Context
      description: Cualquier información adicional que sea relevante / Any additional information that's relevant