# Generated by Django 5.2.9 on 2025-12-27 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
        ("djstripe", "0002_2_10"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="djstripe_subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tenant_subscriptions",
                to="djstripe.subscription",
            ),
        ),
    ]
