# Generated by Django 5.2.11 on 2026-02-05 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_subscription_djstripe_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="max_diagrams",
            field=models.PositiveIntegerField(
                default=5, help_text="Max stored diagrams"
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="max_requests",
            field=models.PositiveIntegerField(
                default=10, help_text="Max integration requests per month"
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="diagrams_used",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="subscription",
            name="requests_used",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="subscription",
            name="usage_reset_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
