#!/usr/bin/env bash
# ───────────────────────────────────────────────────────────────────
# Blue-Green Deploy Script for Proyecto Semilla
# Usage: ./deploy.sh [blue|green]
# Without argument: auto-detects inactive color and deploys to it
# ───────────────────────────────────────────────────────────────────
set -euo pipefail

COMPOSE_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(dirname "$COMPOSE_DIR")"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log()  { echo -e "${BLUE}[deploy]${NC} $1"; }
ok()   { echo -e "${GREEN}[✓]${NC} $1"; }
warn() { echo -e "${YELLOW}[!]${NC} $1"; }
err()  { echo -e "${RED}[✗]${NC} $1" >&2; }

# ── Step 0: Detect current active color ──
get_active_color() {
    if grep -q "web-blue" "$COMPOSE_DIR/nginx/upstream.conf" 2>/dev/null; then
        echo "blue"
    elif grep -q "web-green" "$COMPOSE_DIR/nginx/upstream.conf" 2>/dev/null; then
        echo "green"
    else
        echo "none"
    fi
}

get_inactive_color() {
    local active
    active=$(get_active_color)
    if [ "$active" = "blue" ]; then
        echo "green"
    else
        echo "blue"
    fi
}

# ── Main ──
ACTIVE=$(get_active_color)
TARGET=${1:-$(get_inactive_color)}

log "Current active: ${ACTIVE}"
log "Deploying to: ${TARGET}"

if [ "$ACTIVE" = "$TARGET" ]; then
    err "Cannot deploy to the currently active stack ($TARGET)."
    err "Use: ./deploy.sh $(get_inactive_color)"
    exit 1
fi

# ── Step 1: Pull latest code ──
log "Step 1/7: Pulling latest code..."
cd "$PROJECT_ROOT"
git pull --rebase || { err "git pull failed"; exit 1; }
ok "Code updated"

# ── Step 2: Build the target stack ──
log "Step 2/7: Building ${TARGET} stack..."
cd "$COMPOSE_DIR"
docker compose \
    -f docker-compose.prod.yml \
    -f "docker-compose.${TARGET}.yml" \
    build --no-cache
ok "${TARGET} stack built"

# ── Step 3: Start the target stack ──
log "Step 3/7: Starting ${TARGET} stack..."
docker compose \
    -f docker-compose.prod.yml \
    -f "docker-compose.${TARGET}.yml" \
    up -d
ok "${TARGET} stack started"

# ── Step 4: Run migrations ──
log "Step 4/7: Running migrations on ${TARGET}..."
docker compose \
    -f docker-compose.prod.yml \
    -f "docker-compose.${TARGET}.yml" \
    exec "web-${TARGET}" python manage.py migrate --no-input
ok "Migrations applied"

# ── Step 5: Health check ──
log "Step 5/7: Health check on ${TARGET}..."
MAX_RETRIES=30
RETRY=0
while [ $RETRY -lt $MAX_RETRIES ]; do
    if docker compose \
        -f docker-compose.prod.yml \
        -f "docker-compose.${TARGET}.yml" \
        exec "web-${TARGET}" curl -sf http://localhost:8000/healthz > /dev/null 2>&1; then
        ok "Health check passed"
        break
    fi
    RETRY=$((RETRY + 1))
    log "Waiting for ${TARGET} to be healthy... (${RETRY}/${MAX_RETRIES})"
    sleep 2
done

if [ $RETRY -eq $MAX_RETRIES ]; then
    err "Health check failed after ${MAX_RETRIES} retries. Aborting deploy."
    err "The ${TARGET} stack is running but NOT receiving traffic."
    err "Inspect with: docker compose -f docker-compose.prod.yml -f docker-compose.${TARGET}.yml logs web-${TARGET}"
    exit 1
fi

# ── Step 6: Swap Nginx upstream ──
log "Step 6/7: Swapping Nginx upstream to ${TARGET}..."
cat > "$COMPOSE_DIR/nginx/upstream.conf" <<EOF
# ───────────────────────────────────────────────────────────────────
# ACTIVE UPSTREAM — Auto-generated by deploy.sh
# Deployed: $(date -u '+%Y-%m-%dT%H:%M:%SZ')
# Active color: ${TARGET}
# ───────────────────────────────────────────────────────────────────

upstream web_backend {
    server web-${TARGET}:8000;
}

upstream frontend_backend {
    server frontend-${TARGET}:3000;
}
EOF

# Reload Nginx (zero downtime)
docker compose -f docker-compose.prod.yml exec nginx nginx -s reload
ok "Nginx reloaded — traffic now goes to ${TARGET}"

# ── Step 7: Verify ──
log "Step 7/7: Verifying deployment..."
sleep 3
if curl -sf http://localhost/healthz > /dev/null 2>&1; then
    ok "Deployment verified — ${TARGET} is live!"
else
    warn "Nginx healthz didn't respond. Check logs."
fi

echo ""
echo -e "${GREEN}╔═══════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║  Deploy complete: ${TARGET} is now LIVE   ║${NC}"
echo -e "${GREEN}║  Previous: ${ACTIVE} (still running)      ║${NC}"
echo -e "${GREEN}║                                           ║${NC}"
echo -e "${GREEN}║  Rollback: ./deploy.sh ${ACTIVE}            ║${NC}"
echo -e "${GREEN}╚═══════════════════════════════════════════╝${NC}"
echo ""
log "To stop the old ${ACTIVE} stack:"
log "  docker compose -f docker-compose.prod.yml -f docker-compose.${ACTIVE}.yml down"
