# Generated by Django 5.2.12 on 2026-03-13 08:29

from django.db import migrations

import common.encryption


class Migration(migrations.Migration):

    dependencies = [
        ("mcp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mcpserver",
            name="api_key_hash",
            field=common.encryption.EncryptedCharField(blank=True, default="", max_length=512),
        ),
    ]
