#!/bin/bash

# DAILY REALITY CHECK - Proyecto Semilla
# Ejecutar ANTES de cualquier trabajo de desarrollo

echo "🔍 DAILY REALITY CHECK - $(date)"
echo "=================================="

# Variables de control
DOCKER_STATUS=0
BACKEND_STATUS=0
FRONTEND_STATUS=0
MCP_STATUS=0
OVERALL_STATUS=0

# 1. VERIFICAR DOCKER SERVICES
echo "📦 Checking Docker services..."
docker-compose up -d --wait > /dev/null 2>&1
DOCKER_STATUS=$?

if [ $DOCKER_STATUS -eq 0 ]; then
    echo "✅ Docker services: UP"
else
    echo "❌ Docker services: FAILED TO START"
    OVERALL_STATUS=1
fi

# 2. VERIFICAR BACKEND HEALTH
echo "🔧 Checking Backend health..."
sleep 5  # Give backend time to start
curl -s -f http://localhost:7777/health > /dev/null 2>&1
BACKEND_STATUS=$?

if [ $BACKEND_STATUS -eq 0 ]; then
    echo "✅ Backend health: HEALTHY"
else
    echo "❌ Backend health: UNHEALTHY (http://localhost:7777/health failed)"
    OVERALL_STATUS=1
fi

# 3. VERIFICAR MCP SERVER HEALTH
echo "🧠 Checking MCP Server health..."
sleep 5 # Give MCP server time to start
curl -s -f http://localhost:8001/docs > /dev/null 2>&1
MCP_STATUS=$?

if [ $MCP_STATUS -eq 0 ]; then
    echo "✅ MCP Server health: HEALTHY"
else
    echo "❌ MCP Server health: UNHEALTHY (http://localhost:8001/docs failed)"
    OVERALL_STATUS=1
fi

# 4. VERIFICAR FRONTEND BUILD
echo "🎨 Checking Frontend compilation..."
if [ -d "frontend" ]; then
    cd frontend
    npm run build > /dev/null 2>&1
    FRONTEND_STATUS=$?
    cd ..
    
    if [ $FRONTEND_STATUS -eq 0 ]; then
        echo "✅ Frontend build: SUCCESS"
    else
        echo "❌ Frontend build: COMPILATION ERRORS"
        OVERALL_STATUS=1
    fi
else
    echo "⚠️  Frontend directory not found"
fi

# 5. CALCULAR MÉTRICAS REALES
echo "📊 Calculating real metrics..."

# Contar líneas de código reales
LINES_BACKEND=$(find backend -name "*.py" 2>/dev/null | xargs wc -l 2>/dev/null | tail -1 | awk '{print $1}' || echo "0")
LINES_FRONTEND=$(find frontend -name "*.ts" -o -name "*.tsx" 2>/dev/null | xargs wc -l 2>/dev/null | tail -1 | awk '{print $1}' || echo "0")
TOTAL_LINES=$((LINES_BACKEND + LINES_FRONTEND))

# Contar commits
COMMITS=$(git rev-list --count HEAD 2>/dev/null || echo "0")

# Último commit
LAST_COMMIT=$(git log -1 --pretty=format:"%h - %s (%cr)" 2>/dev/null || echo "No commits found")

# Estado de servicios Docker
DOCKER_SERVICES=$(docker-compose ps --services 2>/dev/null | wc -l || echo "0")
DOCKER_RUNNING=$(docker-compose ps --services --filter status=running 2>/dev/null | wc -l || echo "0")

# 6. GENERAR CURRENT_STATUS.md
echo "📝 Updating CURRENT_STATUS.md..."

mkdir -p docs

cat > docs/CURRENT_STATUS.md << EOF
# 📊 CURRENT STATUS - $(date)
## Auto-generated by daily-check.sh

---

## ✅ SERVICE STATUS (Last checked: $(date))

| Service | Status | Details |
|---------|--------|---------|
| Docker | $([ $DOCKER_STATUS -eq 0 ] && echo "✅ UP" || echo "❌ DOWN") | $DOCKER_RUNNING/$DOCKER_SERVICES services running |
| Backend | $([ $BACKEND_STATUS -eq 0 ] && echo "✅ HEALTHY" || echo "❌ UNHEALTHY") | http://localhost:7777/health |
| MCP Server | $([ $MCP_STATUS -eq 0 ] && echo "✅ HEALTHY" || echo "❌ UNHEALTHY") | http://localhost:8001/docs |
| Frontend | $([ $FRONTEND_STATUS -eq 0 ] && echo "✅ BUILDS OK" || echo "❌ BUILD ERRORS") | npm run build status |

---

## 🔢 REAL METRICS (Auto-calculated)

| Metric | Value | Source |
|--------|-------|--------|
| **Lines of Code (Backend)** | $LINES_BACKEND | find backend -name "*.py" |
| **Lines of Code (Frontend)** | $LINES_FRONTEND | find frontend -name "*.ts*" |
| **Total Lines of Code** | $TOTAL_LINES | Combined count |
| **Git Commits** | $COMMITS | git rev-list --count HEAD |
| **Docker Services** | $DOCKER_RUNNING/$DOCKER_SERVICES | docker-compose ps |

---

## 📝 GIT STATUS

**Last Commit:** $LAST_COMMIT

**Working Directory Status:**
\`\`\`
$(git status --porcelain 2>/dev/null || echo "Git not available")
\`\`\`

---

## 🎯 DEVELOPMENT PRIORITIES

### ✅ Working (Verified $(date))
- Backend APIs responding
- Docker environment stable
- Basic services operational

### 🔧 Needs Attention
$([ $OVERALL_STATUS -ne 0 ] && echo "- **CRITICAL**: Fix failing services before new development" || echo "- No critical issues detected")
$([ $DOCKER_STATUS -ne 0 ] && echo "- **HIGH**: Docker services not starting properly")
$([ $BACKEND_STATUS -ne 0 ] && echo "- **HIGH**: Backend health check failing")
$([ $MCP_STATUS -ne 0 ] && echo "- **HIGH**: MCP Server health check failing")
$([ $FRONTEND_STATUS -ne 0 ] && echo "- **MEDIUM**: Frontend compilation errors")

### 📋 Next Actions (Based on current state)
- [ ] Run daily-check.sh to verify status
- [ ] Fix any failing services before new features
- [ ] Update this status after any significant changes
- [ ] Demo working functionality weekly

---

## ⚠️ WARNINGS

$([ $OVERALL_STATUS -ne 0 ] && echo "🚨 **CRITICAL**: Basic services are not working. Priority #1 is to fix these issues." || echo "✅ All basic services are operational.")

$([ $TOTAL_LINES -lt 1000 ] && echo "📊 **INFO**: Project is in early development stage ($TOTAL_LINES total LOC)")

---

*⚠️ This file is auto-generated by scripts/daily-check.sh*  
*Last updated: $(date)*  
*Manual edits will be overwritten - update via scripts only*

EOF

# 7. RESULTADO FINAL
echo "=================================="

if [ $OVERALL_STATUS -eq 0 ]; then
    echo "🎉 DAILY CHECK: ALL SYSTEMS OPERATIONAL"
    echo "✅ Ready for development work"
else
    echo "🚨 DAILY CHECK: ISSUES DETECTED"
    echo "❌ Fix failing services before continuing"
    echo ""
    echo "🔧 TROUBLESHOOTING:"
    [ $DOCKER_STATUS -ne 0 ] && echo "   - Run: docker-compose down && docker-compose up -d"
    [ $BACKEND_STATUS -ne 0 ] && echo "   - Check: docker-compose logs backend"
    [ $MCP_STATUS -ne 0 ] && echo "   - Check: docker-compose logs mcp_server"
    [ $FRONTEND_STATUS -ne 0 ] && echo "   - Check: cd frontend && npm install && npm run build"
fi

echo ""
echo "📊 Updated docs/CURRENT_STATUS.md with real metrics"
echo "🔍 Review the status file for detailed information"

exit $OVERALL_STATUS
