# Generated by Django 5.2.12 on 2026-03-13 08:29

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0001_initial"),
        ("multitenant", "0003_branding"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("certificate_number", models.CharField(max_length=64, unique=True)),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                ("pdf_url", models.URLField(blank=True, default="")),
            ],
            options={
                "ordering": ["-issued_at"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.PositiveSmallIntegerField(help_text="1-5 stars")),
                ("comment", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("title_en", models.CharField(max_length=255, null=True)),
                ("title_es", models.CharField(max_length=255, null=True)),
                ("title_pt", models.CharField(max_length=255, null=True)),
                ("description", models.TextField(blank=True, default="")),
                ("description_en", models.TextField(blank=True, default="", null=True)),
                ("description_es", models.TextField(blank=True, default="", null=True)),
                ("description_pt", models.TextField(blank=True, default="", null=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["course", "order"],
            },
        ),
        migrations.AlterModelOptions(
            name="course",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="lesson",
            options={"ordering": ["course", "section", "order"]},
        ),
        migrations.AddField(
            model_name="course",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="course",
            name="currency",
            field=models.CharField(default="USD", max_length=3),
        ),
        migrations.AddField(
            model_name="course",
            name="description_en",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="description_es",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="description_mdx",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Rich course description in MDX format",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="description_mdx_en",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Rich course description in MDX format",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="description_mdx_es",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Rich course description in MDX format",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="description_mdx_pt",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Rich course description in MDX format",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="description_pt",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="estimated_hours",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="course",
            name="instructor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="taught_courses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="course",
            name="level",
            field=models.CharField(
                choices=[
                    ("beginner", "Beginner"),
                    ("intermediate", "Intermediate"),
                    ("advanced", "Advanced"),
                ],
                default="beginner",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="preview_video_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="pricing_type",
            field=models.CharField(
                choices=[
                    ("free", "Free"),
                    ("paid", "Paid"),
                    ("subscription", "Subscription"),
                ],
                default="free",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="requirements",
            field=models.JSONField(
                blank=True, default=list, help_text="List of prerequisites"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="slug",
            field=models.SlugField(default="temp-slug", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="course",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("published", "Published"),
                    ("archived", "Archived"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="stripe_price_id",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="course",
            name="stripe_product_id",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="course",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="course",
            name="thumbnail_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="course",
            name="title_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="title_es",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="title_pt",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="course",
            name="what_you_learn",
            field=models.JSONField(
                blank=True, default=list, help_text="Learning outcomes"
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="amount_paid",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="currency",
            field=models.CharField(default="USD", max_length=3),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("completed", "Completed"),
                    ("expired", "Expired"),
                    ("refunded", "Refunded"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="stripe_payment_intent_id",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="lesson",
            name="content_en",
            field=models.TextField(
                blank=True,
                default="",
                help_text="MDX content for the lesson",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="content_es",
            field=models.TextField(
                blank=True,
                default="",
                help_text="MDX content for the lesson",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="content_pt",
            field=models.TextField(
                blank=True,
                default="",
                help_text="MDX content for the lesson",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("video", "Video"),
                    ("text", "Text/MDX"),
                    ("quiz", "Quiz"),
                    ("assignment", "Assignment"),
                ],
                default="text",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="duration_minutes",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="lesson",
            name="is_preview",
            field=models.BooleanField(
                default=False, help_text="Available without enrollment"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="is_published",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="lesson",
            name="slug",
            field=models.SlugField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="lesson",
            name="title_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="lesson",
            name="title_es",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="lesson",
            name="title_pt",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="lesson",
            name="video_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="lessonprogress",
            name="time_spent_seconds",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="course",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="progress",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="0-100 percentage"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="content",
            field=models.TextField(
                blank=True, default="", help_text="MDX content for the lesson"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="course",
            unique_together={("organization", "slug")},
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["organization", "status", "-published_at"],
                name="lms_course_organiz_51ab22_idx",
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="enrollment",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="certificate",
                to="lms.enrollment",
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="certificates",
                to="multitenant.tenant",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="lms.course",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_reviews",
                to="multitenant.tenant",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="lms.course",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lms_sections",
                to="multitenant.tenant",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lessons",
                to="lms.section",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="review",
            unique_together={("user", "course")},
        ),
        migrations.AlterUniqueTogether(
            name="section",
            unique_together={("course", "order")},
        ),
    ]
