# Generated by Django 5.2.12 on 2026-03-13 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("multitenant", "0003_branding"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("name_en", models.CharField(max_length=120, null=True)),
                ("name_es", models.CharField(max_length=120, null=True)),
                ("name_pt", models.CharField(max_length=120, null=True)),
                ("slug", models.SlugField(max_length=120)),
                ("description", models.TextField(blank=True, default="")),
                ("description_en", models.TextField(blank=True, default="", null=True)),
                ("description_es", models.TextField(blank=True, default="", null=True)),
                ("description_pt", models.TextField(blank=True, default="", null=True)),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cms_categories",
                        to="multitenant.tenant",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="cms.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "categories",
                "ordering": ["position", "name"],
                "unique_together": {("organization", "slug")},
            },
        ),
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="cms/media/%Y/%m/")),
                ("filename", models.CharField(max_length=255)),
                ("mime_type", models.CharField(blank=True, default="", max_length=127)),
                ("size_bytes", models.PositiveBigIntegerField(default=0)),
                ("alt_text", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cms_media",
                        to="multitenant.tenant",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cms_media",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContentPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("title_en", models.CharField(max_length=255, null=True)),
                ("title_es", models.CharField(max_length=255, null=True)),
                ("title_pt", models.CharField(max_length=255, null=True)),
                ("slug", models.SlugField(max_length=255)),
                (
                    "excerpt",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Short description for listings",
                    ),
                ),
                (
                    "excerpt_en",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Short description for listings",
                        null=True,
                    ),
                ),
                (
                    "excerpt_es",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Short description for listings",
                        null=True,
                    ),
                ),
                (
                    "excerpt_pt",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Short description for listings",
                        null=True,
                    ),
                ),
                (
                    "body_mdx",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="MDX content (Markdown + JSX components)",
                    ),
                ),
                (
                    "body_mdx_en",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="MDX content (Markdown + JSX components)",
                        null=True,
                    ),
                ),
                (
                    "body_mdx_es",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="MDX content (Markdown + JSX components)",
                        null=True,
                    ),
                ),
                (
                    "body_mdx_pt",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="MDX content (Markdown + JSX components)",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("seo_title", models.CharField(blank=True, default="", max_length=255)),
                (
                    "seo_title_en",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                (
                    "seo_title_es",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                (
                    "seo_title_pt",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                ("seo_description", models.TextField(blank=True, default="")),
                (
                    "seo_description_en",
                    models.TextField(blank=True, default="", null=True),
                ),
                (
                    "seo_description_es",
                    models.TextField(blank=True, default="", null=True),
                ),
                (
                    "seo_description_pt",
                    models.TextField(blank=True, default="", null=True),
                ),
                ("og_image_url", models.URLField(blank=True, default="")),
                ("frontmatter", models.JSONField(blank=True, default=dict)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cms_pages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pages",
                        to="cms.category",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cms_pages",
                        to="multitenant.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "status", "-published_at"],
                        name="cms_content_organiz_6a5725_idx",
                    )
                ],
                "unique_together": {("organization", "slug")},
            },
        ),
    ]
