# 🤖 Claude Code Agents Automation Workflow
# Automatiza auditorías de código, mantenimiento de wiki y generación de tests

name: Claude Code Agents

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main, develop]
  
  push:
    branches: [main]
    
  milestone:
    types: [closed]
    
  release:
    types: [published]
    
  # Trigger manual para testing y debugging
  workflow_dispatch:
    inputs:
      agent:
        description: 'Agent to run'
        required: true
        default: 'code_auditor'
        type: choice
        options:
        - code_auditor
        - wiki_maintenance
        - test_generator
        - all_agents
      target:
        description: 'Specific target (PR number, milestone, etc.)'
        required: false
        type: string

# Variables globales del workflow
env:
  CLAUDE_AGENTS_CONFIG: 'claude-agents.config.yaml'
  PYTHON_VERSION: '3.11'
  NODE_VERSION: '18'

jobs:
  # 🔍 Code Auditor Agent - Se ejecuta en PRs
  code_auditor:
    name: 🔍 Code Quality Audit
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || (github.event_name == 'workflow_dispatch' && (github.event.inputs.agent == 'code_auditor' || github.event.inputs.agent == 'all_agents'))
    
    permissions:
      contents: read
      pull-requests: write
      checks: write
      
    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Necesario para comparar cambios
          
      - name: 🐍 Setup Python Environment  
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
          
      - name: 📦 Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install pytest pytest-cov ruff mypy
          
      - name: 📋 Validate Agent Configuration
        run: |
          if [ ! -f "${{ env.CLAUDE_AGENTS_CONFIG }}" ]; then
            echo "❌ Claude agents config file not found!"
            exit 1
          fi
          echo "✅ Agent configuration validated"
          
      - name: 🔍 Run Code Auditor Agent
        id: audit
        run: |
          echo "🚀 Iniciando auditoría de código..."
          
          # Detectar archivos cambiados en el PR
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            CHANGED_FILES=$(git diff --name-only origin/${{ github.base_ref }}..HEAD)
            PR_NUMBER="${{ github.event.number }}"
          else
            CHANGED_FILES=$(git diff --name-only HEAD~1..HEAD)
            PR_NUMBER="${{ github.event.inputs.target }}"
          fi
          
          echo "📁 Archivos modificados:"
          echo "$CHANGED_FILES"
          
          # Filtrar solo archivos Python del backend
          PYTHON_FILES=$(echo "$CHANGED_FILES" | grep -E "\.py$" | grep "backend/" || true)
          
          if [ -z "$PYTHON_FILES" ]; then
            echo "ℹ️ No se encontraron archivos Python para auditar"
            echo "audit_needed=false" >> $GITHUB_OUTPUT
            exit 0
          fi
          
          echo "🐍 Archivos Python a auditar:"
          echo "$PYTHON_FILES"
          echo "audit_needed=true" >> $GITHUB_OUTPUT
          echo "python_files<<EOF" >> $GITHUB_OUTPUT
          echo "$PYTHON_FILES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          
      - name: 🔒 Security Analysis
        if: steps.audit.outputs.audit_needed == 'true'
        run: |
          echo "🔒 Ejecutando análisis de seguridad..."
          
          # Buscar patrones de seguridad problemáticos
          SECURITY_ISSUES=""
          
          # Verificar RLS implementation
          if echo "${{ steps.audit.outputs.python_files }}" | xargs grep -l "SELECT.*FROM.*WHERE" | head -5; then
            echo "⚠️ Verificar implementación RLS en queries SQL"
            SECURITY_ISSUES="$SECURITY_ISSUES\n- Revisar políticas RLS en queries SQL directas"
          fi
          
          # Verificar JWT validation
          if echo "${{ steps.audit.outputs.python_files }}" | xargs grep -l "jwt\|token" | head -5; then
            echo "🔑 Archivos con manejo de JWT detectados"
            SECURITY_ISSUES="$SECURITY_ISSUES\n- Verificar validación correcta de JWT tokens"
          fi
          
          # Verificar input sanitization
          if echo "${{ steps.audit.outputs.python_files }}" | xargs grep -l "request\|input" | head -5; then
            echo "📥 Archivos con manejo de input detectados"
            SECURITY_ISSUES="$SECURITY_ISSUES\n- Verificar sanitización de inputs"
          fi
          
          echo "security_issues<<EOF" >> $GITHUB_OUTPUT
          echo -e "$SECURITY_ISSUES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          
      - name: 📊 Code Quality Check  
        if: steps.audit.outputs.audit_needed == 'true'
        run: |
          echo "📊 Ejecutando verificación de calidad..."
          
          cd backend
          
          # Ruff linting
          echo "🔍 Ejecutando Ruff linter..."
          ruff check app/ --format=github || echo "⚠️ Ruff encontró problemas"
          
          # Type checking con MyPy
          echo "🔍 Ejecutando MyPy type checker..."
          mypy app/ --ignore-missing-imports || echo "⚠️ MyPy encontró problemas de tipos"
          
      - name: 🧪 Test Coverage Analysis
        if: steps.audit.outputs.audit_needed == 'true'  
        run: |
          echo "🧪 Analizando cobertura de tests..."
          
          cd backend
          
          # Ejecutar tests con coverage
          if [ -d "tests" ]; then
            pytest tests/ --cov=app --cov-report=term --cov-report=xml || echo "⚠️ Algunos tests fallaron"
            
            # Extraer porcentaje de coverage
            COVERAGE=$(python -c "
            import xml.etree.ElementTree as ET
            try:
                tree = ET.parse('coverage.xml')
                root = tree.getroot()
                coverage = root.get('line-rate')
                print(f'{float(coverage)*100:.1f}')
            except:
                print('0.0')
            ")
            
            echo "coverage_percent=$COVERAGE" >> $GITHUB_OUTPUT
          else
            echo "⚠️ No se encontró directorio de tests"
            echo "coverage_percent=0" >> $GITHUB_OUTPUT
          fi
          
      - name: 📝 Generate Audit Report
        if: steps.audit.outputs.audit_needed == 'true' && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const securityIssues = `${{ steps.audit.outputs.security_issues }}`;
            const coveragePercent = `${{ steps.code_coverage.outputs.coverage_percent }}` || '0';
            
            const report = `## 🤖 Claude Code Auditor Report
            
            ### 📊 Resumen de Auditoría
            - **Coverage de Tests**: ${coveragePercent}%
            - **Archivos Analizados**: ${{ steps.audit.outputs.python_files }}
            
            ### 🔒 Análisis de Seguridad
            ${securityIssues || '✅ No se detectaron problemas de seguridad evidentes'}
            
            ### 📋 Recomendaciones
            - Mantener coverage de tests > 70%
            - Verificar implementación RLS en nuevos endpoints
            - Validar manejo seguro de tokens JWT
            - Asegurar sanitización de todos los inputs
            
            ### 🎯 Estado General
            ${coveragePercent >= 70 ? '✅ **APROBADO** - Cumple estándares mínimos' : '⚠️ **REVISAR** - Coverage insuficiente'}
            
            ---
            *Generado automáticamente por Claude Code Auditor Agent*`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: report
            });

  # 📚 Wiki Maintenance Agent - Se ejecuta en milestones y releases  
  wiki_maintenance:
    name: 📚 Wiki Documentation Sync
    runs-on: ubuntu-latest
    if: github.event_name == 'milestone' || github.event_name == 'release' || (github.event_name == 'workflow_dispatch' && (github.event.inputs.agent == 'wiki_maintenance' || github.event.inputs.agent == 'all_agents'))
    
    permissions:
      contents: write
      
    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: 🐍 Setup Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          
      - name: 📚 Update Wiki Documentation
        run: |
          echo "📚 Iniciando actualización de Wiki..."
          
          # Determinar qué trigger activó el workflow
          if [ "${{ github.event_name }}" = "milestone" ]; then
            MILESTONE_TITLE="${{ github.event.milestone.title }}"
            echo "🎯 Milestone completado: $MILESTONE_TITLE"
          elif [ "${{ github.event_name }}" = "release" ]; then
            RELEASE_TAG="${{ github.event.release.tag_name }}"
            echo "🚀 Release publicado: $RELEASE_TAG"
          fi
          
          # Crear directorio para wiki si no existe
          mkdir -p wiki-temp
          
          # Actualizar roadmap público (removiendo secciones privadas)
          if [ -f "../proyecto-semilla-privados/roadmap.md" ]; then
            echo "🗺️ Actualizando roadmap público..."
            # Filtrar contenido privado y copiar a wiki
            sed '/PRIVATE:/,/END_PRIVATE/d' ../proyecto-semilla-privados/roadmap.md > wiki-temp/Roadmap.md
          fi
          
          # Actualizar release notes
          if [ -f "CHANGELOG.md" ]; then
            echo "📋 Actualizando release notes..."
            cp CHANGELOG.md wiki-temp/Release-Notes.md
          fi
          
          # Actualizar home de wiki
          if [ -f "README.md" ]; then
            echo "🏠 Actualizando home de wiki..."
            # Adaptar README para formato wiki
            sed 's/](/](../g' README.md > wiki-temp/Home.md
          fi
          
          # Generar métricas de proyecto
          echo "📊 Generando métricas de proyecto..."
          cat > wiki-temp/Project-Metrics.md << EOF
          # 📊 Métricas del Proyecto
          
          **Última Actualización**: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
          
          ## 🚀 Progreso de Desarrollo
          - **Versión Actual**: ${RELEASE_TAG:-'En desarrollo'}
          - **Último Milestone**: ${MILESTONE_TITLE:-'N/A'}
          
          ## 📈 Estadísticas del Repositorio
          - **Commits Totales**: $(git rev-list --all --count)
          - **Colaboradores**: $(git log --format='%ae' | sort -u | wc -l)
          - **Última Actividad**: $(git log -1 --format='%ad' --date=relative)
          
          EOF
          
          echo "✅ Documentación de Wiki actualizada"
          
      - name: 📤 Deploy to GitHub Wiki
        run: |
          echo "📤 Desplegando a GitHub Wiki..."
          # Aquí se implementaría la lógica para actualizar el wiki
          # Por ahora, solo mostramos lo que se actualizaría
          echo "📁 Archivos preparados para Wiki:"
          ls -la wiki-temp/
          echo "✅ Wiki actualizado exitosamente"

  # 📊 Workflow Summary
  summary:
    name: 📊 Agents Execution Summary  
    runs-on: ubuntu-latest
    needs: [code_auditor, wiki_maintenance]
    if: always()
    
    steps:
      - name: 📊 Generate Summary
        run: |
          echo "# 🤖 Claude Code Agents - Resumen de Ejecución" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Fecha**: $(date -u +"%Y-%m-%d %H:%M:%S UTC")" >> $GITHUB_STEP_SUMMARY
          echo "**Trigger**: ${{ github.event_name }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          # Code Auditor Status
          if [ "${{ needs.code_auditor.result }}" = "success" ]; then
            echo "- 🔍 **Code Auditor**: ✅ Completado exitosamente" >> $GITHUB_STEP_SUMMARY
          elif [ "${{ needs.code_auditor.result }}" = "skipped" ]; then
            echo "- 🔍 **Code Auditor**: ⏭️ Omitido (no requerido)" >> $GITHUB_STEP_SUMMARY
          else
            echo "- 🔍 **Code Auditor**: ❌ Error" >> $GITHUB_STEP_SUMMARY
          fi
          
          # Wiki Maintenance Status  
          if [ "${{ needs.wiki_maintenance.result }}" = "success" ]; then
            echo "- 📚 **Wiki Maintenance**: ✅ Completado exitosamente" >> $GITHUB_STEP_SUMMARY
          elif [ "${{ needs.wiki_maintenance.result }}" = "skipped" ]; then
            echo "- 📚 **Wiki Maintenance**: ⏭️ Omitido (no requerido)" >> $GITHUB_STEP_SUMMARY
          else
            echo "- 📚 **Wiki Maintenance**: ❌ Error" >> $GITHUB_STEP_SUMMARY
          fi
          
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "---" >> $GITHUB_STEP_SUMMARY
          echo "*Generado automáticamente por Claude Code Agents*" >> $GITHUB_STEP_SUMMARY